sonar.projectKey=Vizzuality_agora-paraguay
sonar.organization=vizzuality

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.exclusions=**/routeTree.gen.ts,**/node_modules/**,.output/**,dist/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
